apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: ingresses-changes-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingresses-changes-leader-election-role
  namespace: ingress-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingresses-changes-manager-role
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingresses-changes-leader-election-rolebinding
  namespace: ingress-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingresses-changes-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingresses-changes-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingresses-changes-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: ingresses-changes-controller-manager
  namespace: ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: smuel770/golang-operator-sdk:vbeta-1.0.16
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
